<?php
/**
* 2007-2016 PrestaShop
*
* NOTICE OF LICENSE
*
* This source file is subject to the Academic Free License (AFL 3.0)
* that is bundled with this package in the file LICENSE.txt.
* It is also available through the world-wide-web at this URL:
* http://opensource.org/licenses/afl-3.0.php
* If you did not receive a copy of the license and are unable to
* obtain it through the world-wide-web, please send an email
* to license@prestashop.com so we can send you a copy immediately.
*
* DISCLAIMER
*
* Do not edit or add to this file if you wish to upgrade PrestaShop to newer
* versions in the future. If you wish to customize PrestaShop for your
* needs please refer to http://www.prestashop.com for more information.
*
*  @author    PrestaShop SA <contact@prestashop.com>
*  @copyright 2007-2016 PrestaShop SA
*  @license   http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
*  International Registered Trademark & Property of PrestaShop SA
*/

class SampleDataSlider
{
	public function initData()
	{
		$return = true;
		$languages = Language::getLanguages(true);
		$id_shop = Configuration::get('PS_SHOP_DEFAULT');
		
		$return &= Db::getInstance()->Execute('INSERT IGNORE INTO `'._DB_PREFIX_.'wtslideshow` (`id_wtslideshow`, `position`, `slidedelay`, `transition2d`, `transition3d`, `timeshift`, `active`) VALUES 
		(1, 0, 4000, \'["1"]\', "false", 0, 1),
		(2, 0, 4000, \'["2"]\', "false", 0, 1),
		(3, 0, 4000, \'["3"]\', "false", 0, 1);
		');
		
		$return &= Db::getInstance()->Execute('INSERT IGNORE INTO `'._DB_PREFIX_.'wtslideshow_shop` (`id_wtslideshow`, `id_shop`, `position`, `slidedelay`, `transition2d`, `transition3d`, `timeshift`, `active`) VALUES 
		(1, "'.$id_shop.'", 0, 4000, \'["1"]\', "false", 0, 1),
		(2, "'.$id_shop.'", 0, 4000, \'["2"]\', "false", 0, 1),
		(3, "'.$id_shop.'", 0, 4000, \'["3"]\', "false", 0, 1);
		');
		
		$return &= Db::getInstance()->Execute('INSERT IGNORE INTO `'._DB_PREFIX_.'wtslideshow_options` (`id_wtslideshow_op`, `options`) VALUES 
		(1, \'{"fullwidth":"false","width":"555","height":"489","responsive":"true","responsiveUnder":"0","layersContainer":"0","showmobile":"true","autoStart":"false","pauseOnHover":"true","firstSlide":"1","animateFirstSlide":"true","loops":"0","forceLoopNum":"true","towWaySlideshow":"false","randomSlideshow":"true","skin":"v5","skinsPath":"views\\/css\\/skins\\/","globalBGColor":"transparent","globalBGImage":"false","navPrevNext":"false","navStartStop":"false","navButtons":"true","hoverPrevNext":"true","hoverBottomNav":"true","keybNav":"true","touchNav":"true","showBarTimer":"false","showCircleTimer":"false","thumbnailNavigation":"hover","tnContainerWidth":"60%","tnWidth":"100","tnHeight":"60","tnActiveOpacity":"35","tnInactiveOpacity":"100","autoPlayVideos":"true","autoPauseSlideshow":"auto","youtubePreview":"maxresdefault.jpg","imgPreload":"true","lazyLoad":"true","yourLogo":"false","yourLogoStyle":"left: -10px; top: -10px;","yourLogoLink":"false","yourLogoTarget":"_blank"}\')
		');
		
		$return &= Db::getInstance()->Execute('INSERT IGNORE INTO `'._DB_PREFIX_.'wtslideshow_options_shop` (`id_wtslideshow_op`, `id_shop`, `options`) VALUES 
		(1, "'.$id_shop.'", \'{"fullwidth":"false","width":"555","height":"489","responsive":"true","responsiveUnder":"0","layersContainer":"0","showmobile":"true","autoStart":"false","pauseOnHover":"true","firstSlide":"1","animateFirstSlide":"true","loops":"0","forceLoopNum":"true","towWaySlideshow":"false","randomSlideshow":"true","skin":"v5","skinsPath":"views\\/css\\/skins\\/","globalBGColor":"transparent","globalBGImage":"false","navPrevNext":"false","navStartStop":"false","navButtons":"true","hoverPrevNext":"true","hoverBottomNav":"true","keybNav":"true","touchNav":"true","showBarTimer":"false","showCircleTimer":"false","thumbnailNavigation":"hover","tnContainerWidth":"60%","tnWidth":"100","tnHeight":"60","tnActiveOpacity":"35","tnInactiveOpacity":"100","autoPlayVideos":"true","autoPauseSlideshow":"auto","youtubePreview":"maxresdefault.jpg","imgPreload":"true","lazyLoad":"true","yourLogo":"false","yourLogoStyle":"left: -10px; top: -10px;","yourLogoLink":"false","yourLogoTarget":"_blank"}\')
		');
		
		$return &= Db::getInstance()->Execute('INSERT IGNORE INTO `'._DB_PREFIX_.'wtslideshow_caption` (`id_caption`, `id_wtslideshow`, `type`, `order`, `params`) VALUES 
		(53, 1, 1, 300, \'{"style":"big_white","parallaxlevel":"0","class":"","datax":"59","datay":"224","offsetxin":"80","offsetxout":"-180","offsetyin":"0","offsetyout":"0","delayin":"300","showuntil":"0","durationin":"1000","durationout":"1000","easingin":"easeInOutQuint","easingout":"easeInOutQuint","fadein":"true","fadeout":"true","rotatein":"0","rotateout":"0","rotatexin":"0","rotatexout":"0","rotateyin":"0","rotateyout":"0","scalexin":"1","scalexout":"1","scaleyin":"1","scaleyout":"1","skewxin":"0","skewxout":"0","skewyin":"0","skewyout":"0","transformoriginin":"50% 50% 0","transformoriginout":"50% 50% 0","widthv":"","heightv":"","typev":""}\'),
		(54, 1, 1, 600, \'{"style":"very_big_white","parallaxlevel":"0","class":"","datax":"59","datay":"247","offsetxin":"80","offsetxout":"-180","offsetyin":"0","offsetyout":"0","delayin":"600","showuntil":"0","durationin":"1000","durationout":"1000","easingin":"easeInOutQuint","easingout":"easeInOutQuint","fadein":"true","fadeout":"true","rotatein":"0","rotateout":"0","rotatexin":"0","rotatexout":"0","rotateyin":"0","rotateyout":"0","scalexin":"1","scalexout":"1","scaleyin":"1","scaleyout":"1","skewxin":"0","skewxout":"0","skewyin":"0","skewyout":"0","transformoriginin":"50% 50% 0","transformoriginout":"50% 50% 0","widthv":"","heightv":"","typev":""}\'),
		(55, 1, 1, 900, \'{"style":"medium_text","parallaxlevel":"0","class":"","datax":"59","datay":"322","offsetxin":"80","offsetxout":"-180","offsetyin":"0","offsetyout":"0","delayin":"900","showuntil":"0","durationin":"1000","durationout":"1000","easingin":"easeInOutQuint","easingout":"easeInOutQuint","fadein":"true","fadeout":"true","rotatein":"0","rotateout":"0","rotatexin":"0","rotatexout":"0","rotateyin":"0","rotateyout":"0","scalexin":"1","scalexout":"1","scaleyin":"1","scaleyout":"1","skewxin":"0","skewxout":"0","skewyin":"0","skewyout":"0","transformoriginin":"50% 50% 0","transformoriginout":"50% 50% 0","widthv":"","heightv":"","typev":""}\'),
		(56, 1, 1, 1200, \'{"style":"medium_text","parallaxlevel":"0","class":"","datax":"59","datay":"348","offsetxin":"80","offsetxout":"-180","offsetyin":"0","offsetyout":"0","delayin":"1200","showuntil":"0","durationin":"1000","durationout":"1000","easingin":"easeInOutQuint","easingout":"easeInOutQuint","fadein":"true","fadeout":"true","rotatein":"0","rotateout":"0","rotatexin":"0","rotatexout":"0","rotateyin":"0","rotateyout":"0","scalexin":"1","scalexout":"1","scaleyin":"1","scaleyout":"1","skewxin":"0","skewxout":"0","skewyin":"0","skewyout":"0","transformoriginin":"50% 50% 0","transformoriginout":"50% 50% 0","widthv":"","heightv":"","typev":""}\'),
		(57, 1, 1, 1500, \'{"style":"small_text","parallaxlevel":"0","class":"","datax":"59","datay":"397","offsetxin":"80","offsetxout":"-180","offsetyin":"0","offsetyout":"0","delayin":"1500","showuntil":"0","durationin":"1000","durationout":"1000","easingin":"easeInOutQuint","easingout":"easeInOutQuint","fadein":"true","fadeout":"true","rotatein":"0","rotateout":"0","rotatexin":"0","rotatexout":"0","rotateyin":"0","rotateyout":"0","scalexin":"1","scalexout":"1","scaleyin":"1","scaleyout":"1","skewxin":"0","skewxout":"0","skewyin":"0","skewyout":"0","transformoriginin":"50% 50% 0","transformoriginout":"50% 50% 0","widthv":"","heightv":"","typev":""}\'),
		(58, 2, 1, 300, \'{"style":"big_white","parallaxlevel":"0","class":"","datax":"59","datay":"224","offsetxin":"80","offsetxout":"-180","offsetyin":"0","offsetyout":"0","delayin":"300","showuntil":"0","durationin":"1000","durationout":"1000","easingin":"easeInOutQuint","easingout":"easeInOutQuint","fadein":"true","fadeout":"true","rotatein":"0","rotateout":"0","rotatexin":"0","rotatexout":"0","rotateyin":"0","rotateyout":"0","scalexin":"1","scalexout":"1","scaleyin":"1","scaleyout":"1","skewxin":"0","skewxout":"0","skewyin":"0","skewyout":"0","transformoriginin":"50% 50% 0","transformoriginout":"50% 50% 0","widthv":"","heightv":"","typev":""}\'),
		(59, 2, 1, 600, \'{"style":"very_big_white","parallaxlevel":"0","class":"","datax":"59","datay":"247","offsetxin":"80","offsetxout":"-180","offsetyin":"0","offsetyout":"0","delayin":"600","showuntil":"0","durationin":"1000","durationout":"1000","easingin":"easeInOutQuint","easingout":"easeInOutQuint","fadein":"true","fadeout":"true","rotatein":"0","rotateout":"0","rotatexin":"0","rotatexout":"0","rotateyin":"0","rotateyout":"0","scalexin":"1","scalexout":"1","scaleyin":"1","scaleyout":"1","skewxin":"0","skewxout":"0","skewyin":"0","skewyout":"0","transformoriginin":"50% 50% 0","transformoriginout":"50% 50% 0","widthv":"","heightv":"","typev":""}\'),
		(60, 2, 1, 900, \'{"style":"medium_text","parallaxlevel":"0","class":"","datax":"59","datay":"322","offsetxin":"80","offsetxout":"-180","offsetyin":"0","offsetyout":"0","delayin":"900","showuntil":"0","durationin":"1000","durationout":"1000","easingin":"easeInOutQuint","easingout":"easeInOutQuint","fadein":"true","fadeout":"true","rotatein":"0","rotateout":"0","rotatexin":"0","rotatexout":"0","rotateyin":"0","rotateyout":"0","scalexin":"1","scalexout":"1","scaleyin":"1","scaleyout":"1","skewxin":"0","skewxout":"0","skewyin":"0","skewyout":"0","transformoriginin":"50% 50% 0","transformoriginout":"50% 50% 0","widthv":"","heightv":"","typev":""}\'),
		(61, 2, 1, 1200, \'{"style":"medium_text","parallaxlevel":"0","class":"","datax":"59","datay":"348","offsetxin":"80","offsetxout":"-180","offsetyin":"0","offsetyout":"0","delayin":"1200","showuntil":"0","durationin":"1000","durationout":"1000","easingin":"easeInOutQuint","easingout":"easeInOutQuint","fadein":"true","fadeout":"true","rotatein":"0","rotateout":"0","rotatexin":"0","rotatexout":"0","rotateyin":"0","rotateyout":"0","scalexin":"1","scalexout":"1","scaleyin":"1","scaleyout":"1","skewxin":"0","skewxout":"0","skewyin":"0","skewyout":"0","transformoriginin":"50% 50% 0","transformoriginout":"50% 50% 0","widthv":"","heightv":"","typev":""}\'),
		(62, 2, 1, 1500, \'{"style":"small_text","parallaxlevel":"0","class":"","datax":"59","datay":"397","offsetxin":"80","offsetxout":"-180","offsetyin":"0","offsetyout":"0","delayin":"1500","showuntil":"0","durationin":"1000","durationout":"1000","easingin":"easeInOutQuint","easingout":"easeInOutQuint","fadein":"true","fadeout":"true","rotatein":"0","rotateout":"0","rotatexin":"0","rotatexout":"0","rotateyin":"0","rotateyout":"0","scalexin":"1","scalexout":"1","scaleyin":"1","scaleyout":"1","skewxin":"0","skewxout":"0","skewyin":"0","skewyout":"0","transformoriginin":"50% 50% 0","transformoriginout":"50% 50% 0","widthv":"","heightv":"","typev":""}\'),
		(63, 3, 1, 300, \'{"style":"big_white","parallaxlevel":"0","class":"","datax":"59","datay":"224","offsetxin":"80","offsetxout":"-180","offsetyin":"0","offsetyout":"0","delayin":"300","showuntil":"0","durationin":"1000","durationout":"1000","easingin":"easeInOutQuint","easingout":"easeInOutQuint","fadein":"true","fadeout":"true","rotatein":"0","rotateout":"0","rotatexin":"0","rotatexout":"0","rotateyin":"0","rotateyout":"0","scalexin":"1","scalexout":"1","scaleyin":"1","scaleyout":"1","skewxin":"0","skewxout":"0","skewyin":"0","skewyout":"0","transformoriginin":"50% 50% 0","transformoriginout":"50% 50% 0","widthv":"","heightv":"","typev":""}\'),
		(64, 3, 1, 600, \'{"style":"very_big_white","parallaxlevel":"0","class":"","datax":"59","datay":"247","offsetxin":"80","offsetxout":"-180","offsetyin":"0","offsetyout":"0","delayin":"600","showuntil":"0","durationin":"1000","durationout":"1000","easingin":"easeInOutQuint","easingout":"easeInOutQuint","fadein":"true","fadeout":"true","rotatein":"0","rotateout":"0","rotatexin":"0","rotatexout":"0","rotateyin":"0","rotateyout":"0","scalexin":"1","scalexout":"1","scaleyin":"1","scaleyout":"1","skewxin":"0","skewxout":"0","skewyin":"0","skewyout":"0","transformoriginin":"50% 50% 0","transformoriginout":"50% 50% 0","widthv":"","heightv":"","typev":""}\'),
		(65, 3, 1, 900, \'{"style":"medium_text","parallaxlevel":"0","class":"","datax":"59","datay":"322","offsetxin":"80","offsetxout":"-180","offsetyin":"0","offsetyout":"0","delayin":"900","showuntil":"0","durationin":"1000","durationout":"1000","easingin":"easeInOutQuint","easingout":"easeInOutQuint","fadein":"true","fadeout":"true","rotatein":"0","rotateout":"0","rotatexin":"0","rotatexout":"0","rotateyin":"0","rotateyout":"0","scalexin":"1","scalexout":"1","scaleyin":"1","scaleyout":"1","skewxin":"0","skewxout":"0","skewyin":"0","skewyout":"0","transformoriginin":"50% 50% 0","transformoriginout":"50% 50% 0","widthv":"","heightv":"","typev":""}\'),
		(66, 3, 1, 1200, \'{"style":"medium_text","parallaxlevel":"0","class":"","datax":"59","datay":"348","offsetxin":"80","offsetxout":"-180","offsetyin":"0","offsetyout":"0","delayin":"1200","showuntil":"0","durationin":"1000","durationout":"1000","easingin":"easeInOutQuint","easingout":"easeInOutQuint","fadein":"true","fadeout":"true","rotatein":"0","rotateout":"0","rotatexin":"0","rotatexout":"0","rotateyin":"0","rotateyout":"0","scalexin":"1","scalexout":"1","scaleyin":"1","scaleyout":"1","skewxin":"0","skewxout":"0","skewyin":"0","skewyout":"0","transformoriginin":"50% 50% 0","transformoriginout":"50% 50% 0","widthv":"","heightv":"","typev":""}\'),
		(67, 3, 1, 1500, \'{"style":"small_text","parallaxlevel":"0","class":"","datax":"59","datay":"397","offsetxin":"80","offsetxout":"-180","offsetyin":"0","offsetyout":"0","delayin":"1500","showuntil":"0","durationin":"1000","durationout":"1000","easingin":"easeInOutQuint","easingout":"easeInOutQuint","fadein":"true","fadeout":"true","rotatein":"0","rotateout":"0","rotatexin":"0","rotatexout":"0","rotateyin":"0","rotateyout":"0","scalexin":"1","scalexout":"1","scaleyin":"1","scaleyout":"1","skewxin":"0","skewxout":"0","skewyin":"0","skewyout":"0","transformoriginin":"50% 50% 0","transformoriginout":"50% 50% 0","widthv":"","heightv":"","typev":""}\');');
		
		$return &= Db::getInstance()->Execute('INSERT IGNORE INTO `'._DB_PREFIX_.'wtslideshow_caption_shop` (`id_caption`, `id_wtslideshow`, `id_shop`, `type`, `order`, `params`) VALUES 
		(53, 1, "'.$id_shop.'", 1, 300, \'{"style":"big_white","parallaxlevel":"0","class":"","datax":"59","datay":"224","offsetxin":"80","offsetxout":"-180","offsetyin":"0","offsetyout":"0","delayin":"300","showuntil":"0","durationin":"1000","durationout":"1000","easingin":"easeInOutQuint","easingout":"easeInOutQuint","fadein":"true","fadeout":"true","rotatein":"0","rotateout":"0","rotatexin":"0","rotatexout":"0","rotateyin":"0","rotateyout":"0","scalexin":"1","scalexout":"1","scaleyin":"1","scaleyout":"1","skewxin":"0","skewxout":"0","skewyin":"0","skewyout":"0","transformoriginin":"50% 50% 0","transformoriginout":"50% 50% 0","widthv":"","heightv":"","typev":""}\'),
		(54, 1, "'.$id_shop.'", 1, 600, \'{"style":"very_big_white","parallaxlevel":"0","class":"","datax":"59","datay":"247","offsetxin":"80","offsetxout":"-180","offsetyin":"0","offsetyout":"0","delayin":"600","showuntil":"0","durationin":"1000","durationout":"1000","easingin":"easeInOutQuint","easingout":"easeInOutQuint","fadein":"true","fadeout":"true","rotatein":"0","rotateout":"0","rotatexin":"0","rotatexout":"0","rotateyin":"0","rotateyout":"0","scalexin":"1","scalexout":"1","scaleyin":"1","scaleyout":"1","skewxin":"0","skewxout":"0","skewyin":"0","skewyout":"0","transformoriginin":"50% 50% 0","transformoriginout":"50% 50% 0","widthv":"","heightv":"","typev":""}\'),
		(55, 1, "'.$id_shop.'", 1, 900, \'{"style":"medium_text","parallaxlevel":"0","class":"","datax":"59","datay":"322","offsetxin":"80","offsetxout":"-180","offsetyin":"0","offsetyout":"0","delayin":"900","showuntil":"0","durationin":"1000","durationout":"1000","easingin":"easeInOutQuint","easingout":"easeInOutQuint","fadein":"true","fadeout":"true","rotatein":"0","rotateout":"0","rotatexin":"0","rotatexout":"0","rotateyin":"0","rotateyout":"0","scalexin":"1","scalexout":"1","scaleyin":"1","scaleyout":"1","skewxin":"0","skewxout":"0","skewyin":"0","skewyout":"0","transformoriginin":"50% 50% 0","transformoriginout":"50% 50% 0","widthv":"","heightv":"","typev":""}\'),
		(56, 1, "'.$id_shop.'", 1, 1200, \'{"style":"medium_text","parallaxlevel":"0","class":"","datax":"59","datay":"348","offsetxin":"80","offsetxout":"-180","offsetyin":"0","offsetyout":"0","delayin":"1200","showuntil":"0","durationin":"1000","durationout":"1000","easingin":"easeInOutQuint","easingout":"easeInOutQuint","fadein":"true","fadeout":"true","rotatein":"0","rotateout":"0","rotatexin":"0","rotatexout":"0","rotateyin":"0","rotateyout":"0","scalexin":"1","scalexout":"1","scaleyin":"1","scaleyout":"1","skewxin":"0","skewxout":"0","skewyin":"0","skewyout":"0","transformoriginin":"50% 50% 0","transformoriginout":"50% 50% 0","widthv":"","heightv":"","typev":""}\'),
		(57, 1, "'.$id_shop.'", 1, 1500, \'{"style":"small_text","parallaxlevel":"0","class":"","datax":"59","datay":"397","offsetxin":"80","offsetxout":"-180","offsetyin":"0","offsetyout":"0","delayin":"1500","showuntil":"0","durationin":"1000","durationout":"1000","easingin":"easeInOutQuint","easingout":"easeInOutQuint","fadein":"true","fadeout":"true","rotatein":"0","rotateout":"0","rotatexin":"0","rotatexout":"0","rotateyin":"0","rotateyout":"0","scalexin":"1","scalexout":"1","scaleyin":"1","scaleyout":"1","skewxin":"0","skewxout":"0","skewyin":"0","skewyout":"0","transformoriginin":"50% 50% 0","transformoriginout":"50% 50% 0","widthv":"","heightv":"","typev":""}\'),
		(58, 2, "'.$id_shop.'", 1, 300, \'{"style":"big_white","parallaxlevel":"0","class":"","datax":"59","datay":"224","offsetxin":"80","offsetxout":"-180","offsetyin":"0","offsetyout":"0","delayin":"300","showuntil":"0","durationin":"1000","durationout":"1000","easingin":"easeInOutQuint","easingout":"easeInOutQuint","fadein":"true","fadeout":"true","rotatein":"0","rotateout":"0","rotatexin":"0","rotatexout":"0","rotateyin":"0","rotateyout":"0","scalexin":"1","scalexout":"1","scaleyin":"1","scaleyout":"1","skewxin":"0","skewxout":"0","skewyin":"0","skewyout":"0","transformoriginin":"50% 50% 0","transformoriginout":"50% 50% 0","widthv":"","heightv":"","typev":""}\'),
		(59, 2, "'.$id_shop.'", 1, 600, \'{"style":"very_big_white","parallaxlevel":"0","class":"","datax":"59","datay":"247","offsetxin":"80","offsetxout":"-180","offsetyin":"0","offsetyout":"0","delayin":"600","showuntil":"0","durationin":"1000","durationout":"1000","easingin":"easeInOutQuint","easingout":"easeInOutQuint","fadein":"true","fadeout":"true","rotatein":"0","rotateout":"0","rotatexin":"0","rotatexout":"0","rotateyin":"0","rotateyout":"0","scalexin":"1","scalexout":"1","scaleyin":"1","scaleyout":"1","skewxin":"0","skewxout":"0","skewyin":"0","skewyout":"0","transformoriginin":"50% 50% 0","transformoriginout":"50% 50% 0","widthv":"","heightv":"","typev":""}\'),
		(60, 2, "'.$id_shop.'", 1, 900, \'{"style":"medium_text","parallaxlevel":"0","class":"","datax":"59","datay":"322","offsetxin":"80","offsetxout":"-180","offsetyin":"0","offsetyout":"0","delayin":"900","showuntil":"0","durationin":"1000","durationout":"1000","easingin":"easeInOutQuint","easingout":"easeInOutQuint","fadein":"true","fadeout":"true","rotatein":"0","rotateout":"0","rotatexin":"0","rotatexout":"0","rotateyin":"0","rotateyout":"0","scalexin":"1","scalexout":"1","scaleyin":"1","scaleyout":"1","skewxin":"0","skewxout":"0","skewyin":"0","skewyout":"0","transformoriginin":"50% 50% 0","transformoriginout":"50% 50% 0","widthv":"","heightv":"","typev":""}\'),
		(61, 2, "'.$id_shop.'", 1, 1200, \'{"style":"medium_text","parallaxlevel":"0","class":"","datax":"59","datay":"348","offsetxin":"80","offsetxout":"-180","offsetyin":"0","offsetyout":"0","delayin":"1200","showuntil":"0","durationin":"1000","durationout":"1000","easingin":"easeInOutQuint","easingout":"easeInOutQuint","fadein":"true","fadeout":"true","rotatein":"0","rotateout":"0","rotatexin":"0","rotatexout":"0","rotateyin":"0","rotateyout":"0","scalexin":"1","scalexout":"1","scaleyin":"1","scaleyout":"1","skewxin":"0","skewxout":"0","skewyin":"0","skewyout":"0","transformoriginin":"50% 50% 0","transformoriginout":"50% 50% 0","widthv":"","heightv":"","typev":""}\'),
		(62, 2, "'.$id_shop.'", 1, 1500, \'{"style":"small_text","parallaxlevel":"0","class":"","datax":"59","datay":"397","offsetxin":"80","offsetxout":"-180","offsetyin":"0","offsetyout":"0","delayin":"1500","showuntil":"0","durationin":"1000","durationout":"1000","easingin":"easeInOutQuint","easingout":"easeInOutQuint","fadein":"true","fadeout":"true","rotatein":"0","rotateout":"0","rotatexin":"0","rotatexout":"0","rotateyin":"0","rotateyout":"0","scalexin":"1","scalexout":"1","scaleyin":"1","scaleyout":"1","skewxin":"0","skewxout":"0","skewyin":"0","skewyout":"0","transformoriginin":"50% 50% 0","transformoriginout":"50% 50% 0","widthv":"","heightv":"","typev":""}\'),
		(63, 3, "'.$id_shop.'", 1, 300, \'{"style":"big_white","parallaxlevel":"0","class":"","datax":"59","datay":"224","offsetxin":"80","offsetxout":"-180","offsetyin":"0","offsetyout":"0","delayin":"300","showuntil":"0","durationin":"1000","durationout":"1000","easingin":"easeInOutQuint","easingout":"easeInOutQuint","fadein":"true","fadeout":"true","rotatein":"0","rotateout":"0","rotatexin":"0","rotatexout":"0","rotateyin":"0","rotateyout":"0","scalexin":"1","scalexout":"1","scaleyin":"1","scaleyout":"1","skewxin":"0","skewxout":"0","skewyin":"0","skewyout":"0","transformoriginin":"50% 50% 0","transformoriginout":"50% 50% 0","widthv":"","heightv":"","typev":""}\'),
		(64, 3, "'.$id_shop.'", 1, 600, \'{"style":"very_big_white","parallaxlevel":"0","class":"","datax":"59","datay":"247","offsetxin":"80","offsetxout":"-180","offsetyin":"0","offsetyout":"0","delayin":"600","showuntil":"0","durationin":"1000","durationout":"1000","easingin":"easeInOutQuint","easingout":"easeInOutQuint","fadein":"true","fadeout":"true","rotatein":"0","rotateout":"0","rotatexin":"0","rotatexout":"0","rotateyin":"0","rotateyout":"0","scalexin":"1","scalexout":"1","scaleyin":"1","scaleyout":"1","skewxin":"0","skewxout":"0","skewyin":"0","skewyout":"0","transformoriginin":"50% 50% 0","transformoriginout":"50% 50% 0","widthv":"","heightv":"","typev":""}\'),
		(65, 3, "'.$id_shop.'", 1, 900, \'{"style":"medium_text","parallaxlevel":"0","class":"","datax":"59","datay":"322","offsetxin":"80","offsetxout":"-180","offsetyin":"0","offsetyout":"0","delayin":"900","showuntil":"0","durationin":"1000","durationout":"1000","easingin":"easeInOutQuint","easingout":"easeInOutQuint","fadein":"true","fadeout":"true","rotatein":"0","rotateout":"0","rotatexin":"0","rotatexout":"0","rotateyin":"0","rotateyout":"0","scalexin":"1","scalexout":"1","scaleyin":"1","scaleyout":"1","skewxin":"0","skewxout":"0","skewyin":"0","skewyout":"0","transformoriginin":"50% 50% 0","transformoriginout":"50% 50% 0","widthv":"","heightv":"","typev":""}\'),
		(66, 3, "'.$id_shop.'", 1, 1200, \'{"style":"medium_text","parallaxlevel":"0","class":"","datax":"59","datay":"348","offsetxin":"80","offsetxout":"-180","offsetyin":"0","offsetyout":"0","delayin":"1200","showuntil":"0","durationin":"1000","durationout":"1000","easingin":"easeInOutQuint","easingout":"easeInOutQuint","fadein":"true","fadeout":"true","rotatein":"0","rotateout":"0","rotatexin":"0","rotatexout":"0","rotateyin":"0","rotateyout":"0","scalexin":"1","scalexout":"1","scaleyin":"1","scaleyout":"1","skewxin":"0","skewxout":"0","skewyin":"0","skewyout":"0","transformoriginin":"50% 50% 0","transformoriginout":"50% 50% 0","widthv":"","heightv":"","typev":""}\'),
		(67, 3, "'.$id_shop.'", 1, 1500, \'{"style":"small_text","parallaxlevel":"0","class":"","datax":"59","datay":"397","offsetxin":"80","offsetxout":"-180","offsetyin":"0","offsetyout":"0","delayin":"1500","showuntil":"0","durationin":"1000","durationout":"1000","easingin":"easeInOutQuint","easingout":"easeInOutQuint","fadein":"true","fadeout":"true","rotatein":"0","rotateout":"0","rotatexin":"0","rotatexout":"0","rotateyin":"0","rotateyout":"0","scalexin":"1","scalexout":"1","scaleyin":"1","scaleyout":"1","skewxin":"0","skewxout":"0","skewyin":"0","skewyout":"0","transformoriginin":"50% 50% 0","transformoriginout":"50% 50% 0","widthv":"","heightv":"","typev":""}\');');
		
		foreach ($languages as $language)
		{
			$return &= Db::getInstance()->Execute('INSERT IGNORE INTO `'._DB_PREFIX_.'wtslideshow_lang` (`id_wtslideshow`, `id_lang`, `id_shop`, `title`, `url`, `image`, `thumbnail`) VALUES 
			(1, "'.$language['id_lang'].'", "'.$id_shop.'", "Slider title", "#", "2ffe2877c6d4b005c95ceb0ea0c8c6f08712f946_slider1.jpg", ""),
			(2, "'.$language['id_lang'].'", "'.$id_shop.'", "Slider title", "#", "962cfa73397b45d60470ad903ce9c78599cfacfa_slider2.jpg", ""),
			(3, "'.$language['id_lang'].'", "'.$id_shop.'", "Slider title", "#", "b5474ba9aea7a9e59d6b4bd8dd9477a84471a424_slider3.jpg", "");
			');
			
			$return &= Db::getInstance()->Execute('INSERT IGNORE INTO `'._DB_PREFIX_.'wtslideshow_caption_lang` (`id_caption`, `id_shop`, `id_lang`, `captext`, `capimage`, `capvideo`, `link`) VALUES
			(53, "'.$id_shop.'", "'.$language['id_lang'].'", "good feeling", "Layer Image 0", "Layer Video 0", "#"),
			(54, "'.$id_shop.'", "'.$language['id_lang'].'", "sport&running", "Layer Image 1", "Layer Video 1", "#"),
			(55, "'.$id_shop.'", "'.$language['id_lang'].'", "Phasellus ultrices sagittiset scelerisque mollis nulla ", "Layer Image 2", "Layer Video 2", "#"),
			(56, "'.$id_shop.'", "'.$language['id_lang'].'", "massa venenatis eget", "Layer Image 3", "Layer Video 3", "#"),
			(57, "'.$id_shop.'", "'.$language['id_lang'].'", "shop now", "Layer Image 4", "Layer Video 4", "#"),
			(58, "'.$id_shop.'", "'.$language['id_lang'].'", "hearts on fire", "Layer Image 0", "Layer Video 0", "#"),
			(59, "'.$id_shop.'", "'.$language['id_lang'].'", "new arrvials", "Layer Image 1", "Layer Video 1", "#"),
			(60, "'.$id_shop.'", "'.$language['id_lang'].'", "Phasellus ultrices sagittiset scelerisque mollis nulla ", "Layer Image 2", "Layer Video 2", "#"),
			(61, "'.$id_shop.'", "'.$language['id_lang'].'", "massa venenatis eget", "Layer Image 3", "Layer Video 3", "#"),
			(62, "'.$id_shop.'", "'.$language['id_lang'].'", "shop now", "Layer Image 4", "Layer Video 4", "#"),
			(63, "'.$id_shop.'", "'.$language['id_lang'].'", "the best collection", "Layer Image 0", "Layer Video 0", "#"),
			(64, "'.$id_shop.'", "'.$language['id_lang'].'", "adore&charm", "Layer Image 1", "Layer Video 1", "#"),
			(65, "'.$id_shop.'", "'.$language['id_lang'].'", "Phasellus ultrices sagittiset scelerisque mollis nulla ", "Layer Image 2", "Layer Video 2", "#"),
			(66, "'.$id_shop.'", "'.$language['id_lang'].'", "massa venenatis eget", "Layer Image 3", "Layer Video 3", "#"),
			(67, "'.$id_shop.'", "'.$language['id_lang'].'", "shop now", "Layer Image 4", "Layer Video 4", "#");');
		}
		return $return;
	}
}
?>